# Generated by Django 4.2.7 on 2023-11-11 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.IntegerField()),
                ('saudacao', models.CharField(default='Bem Vindo à Edilson Transfer!', max_length=50)),
                ('titulo', models.CharField(max_length=50)),
                ('texto', models.TextField()),
                ('botao_agendar', models.TextField()),
            ],
        ),
    ]
