# Generated by Django 4.2.7 on 2023-11-11 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='imagem',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='slider',
            name='botao_agendar',
            field=models.TextField(default='Desejo fazer uma cotação com a Edilson Transfer.'),
        ),
    ]
