# Generated by Django 4.2.7 on 2023-11-11 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_slider_imagem_alter_slider_botao_agendar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='botao_agendar',
            field=models.TextField(default='Desejo fazer uma cotação com a Edilson Transfer.', verbose_name='Botão Agendar'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='imagem',
            field=models.ImageField(upload_to='index/hero-slider/'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='ordem',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='slider',
            name='saudacao',
            field=models.CharField(default='Bem Vindo à Edilson Transfer!', max_length=50, verbose_name='saudação'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='titulo',
            field=models.CharField(max_length=50, verbose_name='título'),
        ),
    ]
