# Generated by Django 4.2.7 on 2023-11-11 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_slider_botao_agendar_alter_slider_imagem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='imagem',
            field=models.ImageField(upload_to='index/hero-slider/', verbose_name='Imagem (1920x1280)'),
        ),
    ]
