# Generated by Django 4.2.7 on 2023-11-27 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_slider_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='imagem',
            field=models.ImageField(upload_to='home/hero-slider/', verbose_name='Imagem (1920x1280)'),
        ),
    ]
