# Generated by Django 4.2.7 on 2023-12-11 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viagens', '0002_alter_viagem_data_volta_alter_viagem_email_usuario_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='viagem',
            options={'verbose_name': 'Viagem', 'verbose_name_plural': 'Viagens'},
        ),
        migrations.AddField(
            model_name='viagem',
            name='hora_solicitacao',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Hora da Solicitação'),
        ),
    ]
