# Generated by Django 4.2.7 on 2023-12-11 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viagens', '0003_alter_viagem_options_viagem_hora_solicitacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viagem',
            name='hora_solicitacao',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Hora da Solicitação'),
        ),
    ]
