# Generated by Django 4.2.7 on 2023-12-13 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viagens', '0004_alter_viagem_hora_solicitacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viagem',
            name='hora_solicitacao',
            field=models.DateTimeField(verbose_name='Hora da Solicitação'),
        ),
    ]
